meta_title: "Ghislain - Web Developer"
meta_description: ""Développeur Freelance, je suis à votre disposition pour développer votre site web !""
meta_image: "zguy.png" # Une image dans votre dossier app/assets/images/
