
meta_title: "Ghislain Chavanne - Front-end Développer"
meta_description: "Créer son site web est devenu une priorité pour améliorer sa visibilité! Que votre site soit statique ou dynamique, je m'engage à le développer en m'inspirant de votre univers !"
meta_image: "zguy.png" # Une image dans votre dossier app/assets/images/

