# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d01a1dbbe648da37a41bf0da6764434229575c7b5061717b8e5a1a76c2dbe30611a52a535882fac82afaac5a815a2eb954e4a96ac028a2dea8b346f0d711b5f0

test:
  secret_key_base: ca353235dedd56b8526a88123eac2ac9e0d45d08a147ef07986799e644b397ce5824977a069aa86be29f50f3e104ac58b535e56e3fe510ed4ceb9176fa1d388c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
